## 作業目標

了解 Convolution 卷積的組成

## 作業重點

修改 a_slice_prev 並檢查 Z 的輸出

## 參考資料

介紹三種視覺化方法：

1. 卷積核輸出的視覺化(Visualizing intermediate convnet outputs)：

    即視覺化卷積核經過啟動之後的結果。能夠看到圖像經過卷積之後結果，幫助理解卷積核的作用。


2. 卷積核的視覺化(Visualizing convnets filters)：

    説明我們理解卷積核是如何感受圖像的。


3. 熱度圖視覺化(Visualizing heatmaps of class activation in an image)：

    通過熱度圖，瞭解圖像分類問題中圖像哪些部分起到了關鍵作用，同時可以定位圖像中物體的位置。


[Convnet 介绍（1）](https://blog.csdn.net/douzeyang123/article/details/52635458)

[吴恩达深度学习笔记(73) - 更多的边缘检测方法](https://kknews.cc/zh-sg/news/4nb4lv2.amp)

[Day 06：處理影像的利器 - 卷積神經網路(Convolutional Neural Network)](https://dotblogs.com.tw/greengem/2017/12/17/094150)

[An Intuitive Explanation of Convolutional Neural Networks](https://ujjwalkarn.me/2016/08/11/intuitive-explanation-convnets/)

In [1]:
import numpy as np
np.random.seed(9)

In [2]:
def conv_2d(image, kernel, bias):
    i_m, i_n = image.shape[:2]
    k_m, k_n = kernel.shape[:2]
    o_m, o_n = i_m - k_m + 1, i_n - k_n + 1
    output_image = np.zeros((o_m, o_n,))
    for i in range(o_m):
        for j in range(o_n):
            output_image[i][j] = conv_single_step(image[i:i + k_m, j:j + k_n, :], kernel, bias)
    return output_image

def conv_single_step(a_slice, kernel, bias):
    output = np.sum(a_slice * kernel + bias)
    return float(output)

In [3]:
image, kernel, bias = np.random.randn(16, 9, 3), np.random.randn(6, 6, 3), np.random.randn(1, 1, 1)

print('output:')
print(conv_2d(image, kernel, bias))

output:
[[  3.17091273  34.52281087 -17.11848465   8.54345172]
 [-10.92421146  16.44784494  -1.3636864    6.90447035]
 [  7.88655713   1.5048009    7.68471951  21.04743992]
 [ 11.47613818  -8.63751954  11.26673095  -1.46302725]
 [ 27.17726602   1.92037108  -3.40911132  26.36293974]
 [-10.78696282  12.36328197  -2.02531141  28.51145096]
 [  6.7346136   32.80236827 -11.42748789  13.97453348]
 [ -7.96953962  -9.91512578  18.50866462  -9.0378307 ]
 [  7.87102705  -5.72577119  -5.92672206  -4.57859734]
 [ -5.95141386  -0.22916797  20.70432593   0.23587702]
 [ -3.13413879  14.73839393  -1.08947767  -6.04620101]]
